# *******************************************************************************
# Copyright 2024-2025 Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

name: "Performance AArch64"

on:
  workflow_dispatch:
    inputs:
      onednn_base_hash:
        required: false
        type: string
        description: 'Baseline oneDNN commit'
      onednn_new_hash:
        required: false
        type: string
        description: 'New oneDNN commit'
      acl_base_hash:
        required: false
        type: string
        description: 'Baseline ACL commit'
      acl_new_hash:
        required: false
        type: string
        description: 'New ACL commit'
      num_threads:
        required: false
        type: string
        description: 'Number of threads to use'
      benchdnn_command:
        required: false
        type: string
        description: 'benchdnn command to run'

  workflow_call:

#* Stop stale workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-performance
  cancel-in-progress: true

# Setting this to read-all causes issues with the id-tokens permission
permissions:
  contents: read
  id-token: none

jobs:
  build-oneDNN-base:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout oneDNN
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
            path: oneDNN
  
      - name: Read version file
        id: get-versions
        run: |
          content=`cat ${{ github.workspace }}/oneDNN/.github/automation/aarch64/ci.json`
          content="${content//[$'\t\r\n$ ']}"
          echo "output=$content" >> $GITHUB_OUTPUT

      - name: Build oneDNN base
        uses: ./oneDNN/.github/actions/build-onednn-aarch64
        with:
          artifact_name: onednn-base
          threading: OMP
          toolset: gcc
          build: Release
          testset: SMOKE
          acl_hash: ${{ inputs.acl_base_hash }}
          onednn_hash: ${{ inputs.onednn_base_hash || fromJson(steps.get-versions.outputs.output).dependencies.onednn-base }}
          cache: ${{ inputs.onednn_base_hash == '' && 'true' || 'false'}}

  build-oneDNN-new:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout oneDNN
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
            path: oneDNN

      - name: Build oneDNN new
        uses: ./oneDNN/.github/actions/build-onednn-aarch64
        with:
          artifact_name: onednn-new
          threading: OMP
          toolset: gcc
          build: Release
          testset: SMOKE
          acl_hash: ${{ inputs.acl_new_hash }}
          onednn_hash: ${{ inputs.onednn_new_hash }}

  build-and-test-performance:
    needs: [build-oneDNN-new, build-oneDNN-base]
    strategy:
      fail-fast: false
      matrix:
        config: [
          { name: c7g, label: ah-ubuntu_22_04-c7g_m-100, threading: OMP, toolset: gcc, build: Release, testset: NIGHTLY },
          { name: c8g, label: ah-ubuntu_22_04-c8g_m, threading: OMP, toolset: gcc, build: Release, testset: NIGHTLY }
        ]

    name: ${{ matrix.config.name }}, ${{ matrix.config.toolset }}, ${{ matrix.config.threading }}, ${{ matrix.config.build }}
    runs-on: ${{ matrix.config.label }}
    permissions:
      contents: write
    steps:
      - name: Checkout oneDNN
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
            path: oneDNN

      - name: Read version file
        id: get-versions
        run: |
          content=`cat ${{ github.workspace }}/oneDNN/.github/automation/aarch64/ci.json`
          content="${content//[$'\t\r\n$ ']}"
          echo "output=$content" >> $GITHUB_OUTPUT

      - name: setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt update -y
            sudo apt install -y patchelf libomp-dev g++-${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
            pip install scipy statistics GitPython

      - name: Download oneDNN base
        uses: actions/download-artifact@v6
        with:
          name: onednn-base
          path: oneDNN_pkg

      # Rename oneDNN_pkg to oneDNN_base and fix the runpath for ComputeLibrary
      - name: Prepare oneDNN base for execution
        run: |
          mv oneDNN_pkg oneDNN_base
          chmod -R +x oneDNN_base
          patchelf --add-rpath ${{ github.workspace }}/oneDNN_base/ComputeLibrary/build ${{ github.workspace }}/oneDNN_base/oneDNN/build/src/libdnnl.so.3

      - name: Download oneDNN new
        uses: actions/download-artifact@v6
        with:
          name: onednn-new
          path: oneDNN_pkg

      # Rename oneDNN_pkg to oneDNN_new and fix the runpath for ComputeLibrary
      - name: Prepare oneDNN new for execution
        run: |
          mv oneDNN_pkg oneDNN_new
          chmod -R +x oneDNN_new
          patchelf --add-rpath ${{ github.workspace }}/oneDNN_new/ComputeLibrary/build ${{ github.workspace }}/oneDNN_new/oneDNN/build/src/libdnnl.so.3

      - name: Run nightly performance tests
        if: ${{ inputs.benchdnn_command == '' }}
        shell: bash
        run: |
          bash ${{ github.workspace }}/oneDNN/.github/automation/performance/bench_nightly_performance.sh \
            ${{ github.workspace }}/oneDNN_base/oneDNN/build/tests/benchdnn/benchdnn ${{ github.workspace }}/oneDNN_new/oneDNN/build/tests/benchdnn/benchdnn base.txt new.txt
          python ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt --out-file perf_table.md
        env:
          OMP_NUM_THREADS: ${{ inputs.num_threads || 16 }}

      - name: Update wiki
        if: ${{ (success() || failure()) && inputs.benchdnn_command == '' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ryo-not-rio/wiki') }}
        uses: ./oneDNN/.github/actions/update-wiki
        with:
          command: add-perf
          title: ${{ matrix.config.name }}
          in-file: perf_table.md

      - name: Run custom performance tests
        if: ${{ inputs.benchdnn_command != '' }}
        shell: bash
        run: |
          bash ${{ github.workspace }}/oneDNN/.github/automation/performance/run_benchdnn_compare.sh \
            "${{ github.workspace }}/oneDNN_base/oneDNN/build/tests/benchdnn/benchdnn" \
            "${{ github.workspace }}/oneDNN_new/oneDNN/build/tests/benchdnn/benchdnn" \
            base.txt new.txt "$BENCHDNN_COMMAND"
        env:
          OMP_NUM_THREADS: ${{ inputs.num_threads || 16 }}
          BENCHDNN_COMMAND: ${{ inputs.benchdnn_command }}

      - name: Print speed comparisons
        if: ${{ (success() || failure()) && inputs.benchdnn_command != '' }}
        run: python3 ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt --out-file perf_results.md; cat perf_results.md >> $GITHUB_STEP_SUMMARY

  #* This job adds a check named "Nightly Performance AArch64" that represents overall
  #* workflow status and can be used in branch rulesets
  status:
    needs: build-and-test-performance
    runs-on: ubuntu-24.04
    name: "Nightly Performance AArch64"
    steps:
      - name: Print success
        run: echo Success
