# *******************************************************************************
# Copyright 2024-2025 Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

name: "Performance AArch64"

on:
  workflow_dispatch:
    inputs:
      onednn_base_hash:
        required: false
        type: string
        description: 'Baseline oneDNN commit'
      onednn_new_hash:
        required: false
        type: string
        description: 'New oneDNN commit'
      acl_base_hash:
        required: false
        type: string
        description: 'Baseline ACL commit'
      acl_new_hash:
        required: false
        type: string
        description: 'New ACL commit'
      num_threads:
        required: false
        type: string
        description: 'Number of threads to use'
      benchdnn_command:
        required: false
        type: string
        description: 'benchdnn command to run'

  workflow_call:

#* Stop stale workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-performance
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-acl-base:
    uses: ./.github/workflows/aarch64-acl.yml
    with:
      acl_hash: ${{ inputs.acl_base_hash }}

  build-acl-new:
    uses: ./.github/workflows/aarch64-acl.yml
    with:
      acl_hash: ${{ inputs.acl_new_hash }}

  build-and-test-performance:
    needs: [build-acl-base, build-acl-new]
    strategy:
      matrix:
        config: [
          { name: c7g, label: ah-ubuntu_22_04-c7g_m-100, threading: OMP, toolset: gcc, build: Release, testset: NIGHTLY }
        ]

    name: ${{ matrix.config.name }}, ${{ matrix.config.toolset }}, ${{ matrix.config.threading }}, ${{ matrix.config.build }}
    runs-on: ${{ matrix.config.label }}
    steps:

      - name: Checkout oneDNN
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: oneDNN

      # Note: This will create a github actions cache
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@56d043d188c3612951d8755da8f4b709ec951ad6 # v3.31.6
        with:
          cmakeVersion: 3.31.0
          ninjaVersion: 1.12.0

      - if: ${{ matrix.config.threading == 'OMP' }}
        name: Install openmp
        run: |
          sudo apt install -y libomp-dev

      - name: Read version file
        id: get-versions
        run: |
          content=`cat ${{ github.workspace }}/oneDNN/.github/automation/aarch64/ci.json`
          content="${content//[$'\t\r\n$ ']}"
          echo "output=$content" >> $GITHUB_OUTPUT

      - name: Install gcc
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update -y
          sudo apt install -y g++-${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}

      - name: setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install scipy
        if: ${{ matrix.config.build == 'Release' }}
        run: pip install scipy statistics

      - name: Clone base ACL
        run: ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
        env:
          ACL_ACTION: clone
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary
          ACL_VERSION: ${{ inputs.acl_base_hash || fromJson(steps.get-versions.outputs.output).dependencies.acl }}

      - name: Get system name
        id: get_system_name
        run: (echo "SystemName=$(uname)") >> $GITHUB_OUTPUT

      - name: Get ACL commit hash for cache key
        id: get_acl_commit_hash_base
        run: |
          cd ${{ github.workspace }}/ComputeLibrary && echo "ACLCommitHash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Restore base cached ACL
        id: cache-acl-restore-base
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ steps.get_system_name.outputs.SystemName }}-acl-${{ matrix.config.toolset }}-${{ matrix.config.build }}-${{ steps.get_acl_commit_hash_base.outputs.ACLCommitHash }}
          path: ${{ github.workspace }}/ComputeLibrary/build
          fail-on-cache-miss: true

      - name: Rename to ComputeLibrary_base
        run: mv ${{ github.workspace }}/ComputeLibrary ${{ github.workspace }}/ComputeLibrary_base

      - name: Clone new ACL
        run: ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
        env:
          ACL_ACTION: clone
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary
          ACL_VERSION: ${{ inputs.acl_new_hash || fromJson(steps.get-versions.outputs.output).dependencies.acl }}

      - name: Get ACL commit hash for cache key
        id: get_acl_commit_hash_new
        run: |
          cd ${{ github.workspace }}/ComputeLibrary && echo "ACLCommitHash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Restore new cached ACL
        id: cache-acl-restore-new
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ steps.get_system_name.outputs.SystemName }}-acl-${{ matrix.config.toolset }}-${{ matrix.config.build }}-${{ steps.get_acl_commit_hash_new.outputs.ACLCommitHash }}
          path: ${{ github.workspace }}/ComputeLibrary/build
          fail-on-cache-miss: true

      - name: Move to ComputeLibrary_new
        run: mv ${{ github.workspace }}/ComputeLibrary ${{ github.workspace }}/ComputeLibrary_new

      - name: Checkout oneDNN base
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{inputs.onednn_base_hash || fromJson(steps.get-versions.outputs.output).dependencies.onednn-base }}
          path: oneDNN_base

      - name: Checkout oneDNN new
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # when the input is non empty use it otherwise falls back to github.sha
          ref: ${{ inputs.onednn_new_hash != '' && inputs.onednn_new_hash || github.sha }}
          path: oneDNN_new

      - name: Configure oneDNN base
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_base
        env:
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary_base
          BUILD_TOOLSET: ${{ matrix.config.toolset }}
          CMAKE_BUILD_TYPE: ${{ matrix.config.build }}
          CMAKE_GENERATOR: Ninja
          GCC_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
          ONEDNN_ACTION: configure
          ONEDNN_TEST_SET: ${{ matrix.config.testset }}
          ONEDNN_THREADING: ${{ matrix.config.threading }}

      - name: Build oneDNN base
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_base
        env:
          ONEDNN_ACTION: build

      - name: Configure oneDNN new
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_new
        env:
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary_new
          BUILD_TOOLSET: ${{ matrix.config.toolset }}
          CMAKE_BUILD_TYPE: ${{ matrix.config.build }}
          CMAKE_GENERATOR: Ninja
          GCC_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
          ONEDNN_ACTION: configure
          ONEDNN_TEST_SET: ${{ matrix.config.testset }}
          ONEDNN_THREADING: ${{ matrix.config.threading }}

      - name: Build oneDNN new
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_new
        env:
          ONEDNN_ACTION: build

      - name: Run nightly performance tests
        if: ${{ inputs.benchdnn_command == '' }}
        shell: bash
        run: |
          OMP_NUM_THREADS=${{ inputs.num_threads || 16 }} bash ${{ github.workspace }}/oneDNN/.github/automation/performance/bench_nightly_performance.sh ${{ github.workspace }}/oneDNN_base/build/tests/benchdnn/benchdnn ${{ github.workspace }}/oneDNN_new/build/tests/benchdnn/benchdnn base.txt new.txt
          python ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt --check

      - name: Run custom performance tests
        if: ${{ inputs.benchdnn_command != '' }}
        shell: bash
        run: |
          OMP_NUM_THREADS=${{ inputs.num_threads || 16 }} \
          bash ${{ github.workspace }}/oneDNN/.github/automation/performance/run_benchdnn_compare.sh \
            "${{ github.workspace }}/oneDNN_base/build/tests/benchdnn/benchdnn" \
            "${{ github.workspace }}/oneDNN_new/build/tests/benchdnn/benchdnn" \
            base.txt new.txt ${{ inputs.benchdnn_command }}

      - name: Print speed comparisons
        if: ${{ inputs.benchdnn_command != '' }}
        run: |
          python3 ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt

  #* This job adds a check named "Nightly Performance AArch64" that represents overall
  #* workflow status and can be used in branch rulesets
  status:
    needs: build-and-test-performance
    runs-on: ubuntu-latest
    name: "Nightly Performance AArch64"
    steps:
      - name: Print success
        run: echo Success
